<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mentorpi_perception</name>
  <version>0.9.1</version>
  <description>Person perception: Detection2D plus depth range; NN lives in mentorpi_person_detect.</description>
  <maintainer email="lunix0x@gmail.com">Roman Kalashnikov</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>mentorpi_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
