<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mentorpi_voice</name>
  <version>0.2.0</version>
  <description>Voice command recognition (voice_command node).</description>
  <maintainer email="lunix0x@gmail.com">Roman Kalashnikov</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>rclcpp</depend>
  <depend>mentorpi_msgs</depend>
  <depend>std_msgs</depend>
  <build_depend>libasound2-dev</build_depend>
  <build_depend>nlohmann-json3-dev</build_depend>
  <exec_depend>libasound2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
